# Global Variables

title: Parallax Gap Fix
description: >
  A fix for a bug in pure CSS parallax layouts.
keywords: # a YAML list. optional; only used by some older search engines.
baseurl: /parallax-gap-fix
url: https://dawaltconley.github.io
og_image: # default og image used for entire site; can be overridden if specified in page or collection frontmatter
google_analytics: # tracking number
permalink: /:title/ # default permalink structure for pages
timezone: America/New_York # used for liquid-generated datetimes
emptyArray: [] # variable for easy array creation
auto_scroll: false # enables smooth scrolling for all same-page links using zenscroll
bg_testing: false # turn on to enable the bg-testing.html include

# Build settings

markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "node_modules"
  - "gulpfile.js"
  - "images/test"
